version: 0.2

phases:
  build:
    commands:
      - echo Build phase...
      - mvn clean package
  post_build:
  commands:
    - echo Build completed successfully
artifacts:
  files:
    - target/s3-example.jar
  discard-paths: yes